name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace with your build script

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "dangolavishek@gmail.com"
          git config --global user.name "Avishek Dangol"

          git checkout --orphan gh-pages
          git --set-upstream-to=origin/main
          git pull origin main

          rm -rf *
          mv dist/* .

          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force

